services:
  - type: web
    name: diplom-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: diplom-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PORT
        value: 8000
    docker:
      compose:
        services:
          redis:
            image: redis:6
            ports:
              - '6379:6379'
        volumes:
          redis_data: {}

  - type: redis
    name: diplom-redis
    ipAllowList: []
    plan: free

databases:
  - name: diplom-db
    databaseName: mediadb
    user: diplom
    plan: free

volumes:
  - name: redis_data
    mountPath: /data
