services:
  - type: web
    name: diplom-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: diplom-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2  # Уменьшено для free tier
      - key: PYTHONUNBUFFERED
        value: 1

databases:
  - name: diplom-db
    databaseName: mediadb
    user: diplom
    plan: free
